ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.HttpKt.configureHttp
      - com.example.MonitoringKt.configureMonitoring
      - com.example.SerializationKt.configureSerialization
      - com.example.StatusPagesKt.configureStatusPages
      - com.example.WebsocketsKt.configureWebsockets
      - com.example.RequestValidationKt.configureRequestValidation
      - com.example.RateLimitingKt.configureRateLimiting
      - com.example.RoutingKt.configureRouting
